name: Deploy ADMIN (PROD)

on:
  workflow_dispatch:

concurrency:
  group: deploy-admin-prod
  cancel-in-progress: false

jobs:
  deploy:
    name: Build on VPS & restart app
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VPS & deploy PROD
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /var/www/homecyclhome/homecyclhome_admin

            # sécurité git
            git config --global --add safe.directory /var/www/homecyclhome/homecyclhome_admin

            # sync code
            git fetch origin main
            git reset --hard origin/main

            # build & run (projet Compose figé pour PROD)
            DOCKER_BUILDKIT=1 docker compose -p homecyclhome_admin build --pull
            docker compose -p homecyclhome_admin up -d --no-deps admin

            docker image prune -f || true
            docker compose -p homecyclhome_admin ps
            docker compose -p homecyclhome_admin logs --since=1m admin || true
